### ISSUE TITLE
[BUGS] [SERVER-SIDE] [COLUMNS] It's doing extra request for each column

### ISSUE THREAD

**Issue by ArseniyX** [grid-js/gridjs#1317] opened 2023-02-18 14:14 UTC
**Describe the bug**
The library doing request for each columns that actually unwanted because it increase traffic and make problems to debug

**To Reproduce**
1. Go to https://gridjs.io/docs/examples/server-side-sort
2. clear networks
3. add 3 columns to the example code or copy full code below
4. look networks
expected: 1 request
current: 5 requests

<img width="996" alt="image" src="https://user-images.githubusercontent.com/41956571/219870547-db41d326-9edd-4513-a3eb-de9fcf4f6114.png">

```javascript
const grid = new Grid({
  sort: {
    multiColumn: false,
    server: {
      url: (prev, columns) => {
       if (!columns.length) return prev;
       
       const col = columns[0];
       const dir = col.direction === 1 ? 'asc' : 'desc';
       let colName = ['name', 'rarity', '1', '2', '3'][col.index];
       
       return `${prev}&order=${colName}&dir=${dir}`;
     }
    }
  },
  columns: [
   'Name',
   'Rarity',
   '1',
   '2',
   '3',
   {
     name: 'Image',
     width: '30%',
     sort: false,
     formatter: (img) => html(`<center><img src='${img}'/></center>`)
   }
  ],
  server: {
    url: 'https://api.scryfall.com/cards/search?q=Inspiring',
    then: data => data.data.map(card => [card.name, card.rarity, card.image_uris.small]),
    total: data => data.total_cards
  } 
});
```

**Comment by rbdmorgan** [comment] 2023-02-25 11:28
Just came across this as well. You can reproduce it with the example here:

https://gridjs.io/docs/examples/server-side-sort

![image](https://user-images.githubusercontent.com/77004274/221354446-8aa234f7-08af-4c29-99e3-534dfcf69222.png)

**Comment by rbdmorgan** [comment] 2023-02-25 14:23
It fires off the duplicate requests on load as well.

So if you have 3 columns it does 4 requests on load and then 3 requests on each sort (th click).

**Comment by rbdmorgan** [comment] 2023-02-26 11:36
Unfortunately the server side sorting and pagination appears to be broken.

If you have both set up and click on a sort header, `pagination.server()` gets called 4 times and then `sort.server()` gets called 2 times.

The first 2 sort calls don't include the params and the pagination calls shouldn't happen at all. So depending on which call "wins" and refreshes the grid you usually end up with a grid that isn't in the correct state, plus you've hit the server 6 times rather than 1.

I guess it's a case of React duplicating/bubbling events, not as much of a problem if you're not hitting a server, so probably doesn't show up in the client side sorting and pagination.

**Comment by opheus2** [comment] 2023-03-16 23:13
Any update on this... without the sorting for me, for every column, a new request is made

**Comment by crpozo** [comment] 2023-03-22 12:55
I have the same problem. It's a great idea and library but this is an important bug. I guess adding a loading screen or something similar but this will not solved it entirely.

**Comment by crpozo** [comment] 2023-03-22 13:13
Quick solution: Downgrade to version 5. All features seems to work fine, at least the ones I'm using.

**Comment by ArseniyX** [comment] 2023-03-22 21:21
> Quick solution: Downgrade to version 5. All features seems to work fine, at least the ones I'm using.

Thanks, thats better than nothing anyway, I tried to find real solution without success

**Comment by garidium** [comment] 2023-03-27 15:15
I just ran across this as well today.

**Comment by Marin-Matosevic** [comment] 2023-04-06 12:07
I had faced a similar issue while using the RowSelection plugin, when attempting to select a row immediately after the page load, the selection would disappear. It was frustrating and appeared to be buggy. To overcome this, I implemented a simple workaround by creating a custom function that retrieves data from my endpoint.

Below is the implementation of the custom function, which I assigned as the data parameter inside the new Grid({})
Since is used with WordPress endpoint, I have nonce parameter but you can remove it.

``` JS
async function fetchData( endpoint, nonce ) {
    try {
        const response = await fetch( endpoint, {
            headers: {
                'X-WP-Nonce': nonce,
            },
        } );
        const data = await response.json();

        return data;
    } catch ( error ) {
        console.error( error );
    }
}
```

and inside new Grid({})

```JS
data: await fetchData( '/wp-json/cool-endpoint/v1/data', nonce )
```

**Comment by mrtorks** [comment] 2023-05-16 12:54
> I had faced a similar issue while using the RowSelection plugin, when attempting to select a row immediately after the page load, the selection would disappear. It was frustrating and appeared to be buggy. To overcome this, I implemented a simple workaround by creating a custom function that retrieves data from my endpoint.
> 
> Below is the implementation of the custom function, which I assigned as the data parameter inside the new Grid({}) Since is used with WordPress endpoint, I have nonce parameter but you can remove it.
> 
> ```js
> async function fetchData( endpoint, nonce ) {
>     try {
>         const response = await fetch( endpoint, {
>             headers: {
>                 'X-WP-Nonce': nonce,
>             },
>         } );
>         const data = await response.json();
> 
>         return data;
>     } catch ( error ) {
>         console.error( error );
>     }
> }
> ```
> 
> and inside new Grid({})
> 
> ```js
> data: await fetchData( '/wp-json/cool-endpoint/v1/data', nonce )
> ```

With this workaround, can you confirm it works with server side import, search, pagination as well as sort? If not could you provide a template for so. It would really be appreciated.

**Comment by Marin-Matosevic** [comment] 2023-05-19 06:38
@mrtorks Yes, it works fine with pagination and sort. Not sure about search since I don't use it, but I don't see any reason why it wouldn't work.

**Comment by AleAmex** [comment] 2023-06-22 12:27
Same problem for me 
https://stackoverflow.com/questions/75899156/when-try-server-side-sorting-with-grid-js-it-does-multiple-calls-to-the-server-t/76521809

Hope it will be solved soon

**Comment by rendorHaevyn** [comment] 2023-06-29 04:19
> Quick solution: Downgrade to version 5. All features seems to work fine, at least the ones I'm using.

Confirmed - downgrading to 5.0.2 prevents the request overload.

`<script src="https://unpkg.com/gridjs@5.0.2/dist/gridjs.umd.js"></script>`

**Comment by sabatale** [comment] 2023-08-03 20:33
@rendorHaevyn Have you tested on 5.1.0?

**Comment by omerserif** [comment] 2023-08-06 08:35
I am using the latest version and the problem persists.

When will the solution be?

**Comment by middleftw** [comment] 2023-08-30 10:36
I stumbled upon the same problem. I don't have sorting yet, but it happens when I use `forceRender`.

**Comment by vkresch** [comment] 2023-11-13 23:08
Same issue. When making this many requests I cannot set an initial page and it just resets to zero.

**Comment by afshinm** [comment] 2023-12-30 15:33
Apologies for this issue. I have a fix for this that should address this issue and improve the overall rendering performance of the library: https://github.com/grid-js/gridjs/pull/1408

**Closed** 2024-01-09 09:12 UTC

**Comment by afshinm** [comment] 2024-01-14 17:40
A new version is now available. Please try v6.1.0 https://www.npmjs.com/package/gridjs

**Comment by charlesmudy** [comment] 2024-03-06 18:18
@afshinm this is still happening with v6.2.0 as of today. Not sure why and the fix to this. We are using handle option with alert, now causing the application to alert multiple times.

**Comment by RegistrosTI** [comment] 2024-07-15 06:40
I confirm that this issue still exists in version 6.2.0. When the sort server is configured, it makes a fetch for every column.
